name = input('Hi user, can you tell me your name? ')
print('Hi', name, 'nice to meet you.')
weight = input('What is your weight(in kg)? ')
print('You are', weight,'kg')
height = input('Excellent, now how tall are you(in cm)? ')
print('Well,', height, 'cm is not quite tall as I thought. JK!')